name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libffi-dev \
          libssl-dev \
          autoconf \
          automake \
          libtool \
          pkg-config

    - name: Install buildozer
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer cython virtualenv

    - name: Prepare Android SDK
      run: |
        buildozer android debug || true

    - name: Force accept Android licenses
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" >> $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $HOME/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
